-- =====================================================================
-- Taurus Bike Shop - Product Image Update Script
-- =====================================================================

MERGE INTO [dbo].[ProductImage] AS target
USING (
    -- Get Product IDs by name
    SELECT p.ProductId, updates.ImageUrl
    FROM [dbo].[Product] p
    JOIN (
        VALUES
            ('Weapon Race w/ Palm Rest', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426834/Weapon_Race_With_Palm_Rest_yto3zu.jpg'),
            ('SR Suntour XCR 32 BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426577/SR_Suntour_XCR_32_BOOST_knwkdn.jpg'),
            ('Genova Mars', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427050/Genova_Mars_i34cdi.jpg'),
            ('Cult Odyssey Hydro Brakes 27.5', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426713/Cult_Odyssey_Hydro_Brakes_27.5_bvmpfr.jpg'),
            ('Manitou Markhor BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426553/Manitou_Markhor_BOOST_ct7fkc.jpg'),
            ('Sagmit Oilslick', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427019/Sagmit_oilslick_w91p3v.jpg'),
            ('Toseek Chester 700c Disc Brake ALLOY (2x9)', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426703/Toseek_Chester_700c_Disc_Brake_ALLOY_2x9_jedbj2.webp'),
            ('Seer Polymer Bartape', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426838/Seer_Polymer_Bartape_lc6dzk.jpg'),
            ('Speedone Pilot', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426982/Speedone_Pilot_ct6pje.jpg'),
            ('Maxxis Ikon 27.5 x 2.20 Tanwall', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427128/Maxxis_Ikon_27.5_tanwall_ewp9yr.jpg'),
            ('WTB i21 Tubeless Ready', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426992/WTB_i21_mnvcle.jpg'),
            ('Kore Realm 2.4', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427008/Kore_Realm_2.4_hye5ae.jpg'),
            ('Speedone Soldier', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426984/Speedone_Soldier_s6b6w6.jpg'),
            ('Pinewood Challenger', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426726/Pinewood_Challenger_jueqfe.jpg'),
            ('Sagmit Brooklyn 3.0', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426788/Sagmit_Brooklyn_tzuter.jpg'),
            ('Sagmit Aero', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426987/Samit_Aero_mtjrjm.jpg'),
            ('SRAM NX Eagle 12spd WITH BB', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427154/SRAM_NX_eagle_12spd_yc7jrg.jpg'),
            ('Silicon Grip Seer 5mm', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426827/Silicon_SEER_Grip_5mm_difria.jpg'),
            ('Pedal Sagmit 614', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426914/Sagmit_618_iipjmh.jpg'),
            ('Kespor Stork Feather CX 1.0 2022', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426720/Kespor_Stork_Feather_CX_1.0_2022_fglrpr.jpg'),
            ('Pinewood Lancer 1.0 2022 Gravel RX (2x9)', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426728/Pinewood_Lancer_1.0_2022_Gravel_RX_2x9_mkciit.jpg'),
            ('SIZE 20 LEO TUBE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427123/Leo_tire_size_20_xdqvlm.jpg'),
            ('ZEE M640 10spd Upkit', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427157/ZEE_M640_10spd_Upkit_ipkwcm.jpg'),
            ('SIZE 16 TUBE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427117/Size_16_tube_f9xoww.webp'),
            ('Maxxis Crossmark II 27.5 x 2.25', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427147/Maxxis_Crossmark_II_27.5_x_2.25_m0v7nl.jpg'),
            ('10SPD KMC Chain X Series GREY', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426635/KMC_CHAIN_X_SERIES_10_TO_12_SPEED_yosheh.jpg'),
            ('Weapon Savage Stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427081/Weapon_Savage_Stem_st4mkb.jpg'),
            ('2021 Pinewood Climber CARBON 27.5', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426709/2021_Pinewood_Climber_CARBON_27.5_mknm3n.jpg'),
            ('SAGMIT TUBE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427112/Sagmit_tube_29_fkg8oe.webp'),
            ('SR Suntour Epixon Stealth', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426565/SR_Suntour_Epixon_Stealth_q6h3ux.jpg'),
            ('Jalco Wellington Tubeless Ready', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427003/Jalco_Wellington_xfnqcx.jpg'),
            ('8 SPEED SUMC Oilslick 116Links With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426645/SUMC_OILSLICK_8_10_11SPD_okx6nk.jpg'),
            ('Weapon Animal Stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427089/Weapon_Animal_Stem_tejbbp.jpg'),
            ('Kore Realm 4.2', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426974/Kore_Realm_4.2_xrdbud.jpg'),
            ('Handle Bar Pro Koryak', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426778/Handle_Bar_Pro_Koryak_cfq79g.jpg'),
            ('Seer Super Lite Bar tape', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426820/Seer_Super_Lite_elxxb9.jpg'),
            ('COLE NX 27.5 TRI-FACTOR 2021', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426711/COLE_NX_27.5_TRI-FACTOR_2021_czjmyq.jpg'),
            ('Saturn Calypso', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426699/Saturn_Calypso_voz4o9.jpg'),
            ('Velo Plush', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427042/Velo_Push_ulmyxl.jpg'),
            ('Weapon Rocket', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426589/Weapon_Rocket_Black_yjahxl.jpg'),
            ('10SPD KMC Chain X Series GOLD', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426637/KMC_CHAIN_X_SERIES_GOLD_9_10_AND_12_SPD_qtbpjh.jpg'),
            ('Sagmit Static', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426782/Sagmit_Static_bl4jmv.jpg'),
            ('Sagmit EVO3', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426871/Sagmit_Evo_3_ao5hxs.jpg'),
            ('12spd LTwoo AX Upkit with IXF crank', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427159/12spd_LTwoo_AX_Upkit_ndv2ue.jpg'),
            ('Pedal Sagmit 610', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426916/Sagmit_610_awm9h9.jpg'),
            ('11SPD KMC Chain X Series GREY', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426635/KMC_CHAIN_X_SERIES_10_TO_12_SPEED_yosheh.jpg'),
            ('Weapon Rifle', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426583/Weapon_Rifle_it6dgy.jpg'),
            ('Aeroic AIR FORK', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426529/Aeroic_Air_Fork_vxnp3r.jpg'),
            ('12 SPEED SUMC CP With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426641/SUMC_8_TO_12SPD_ctvl9s.jpg'),
            ('Genova Jupiter', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427053/Genova_Jupiter_pbhtfz.jpg'),
            ('8 SPEED SUMC CP With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426641/SUMC_8_TO_12SPD_ctvl9s.jpg'),
            ('Handle Post Controltech ONE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427078/HandlePost_ControlTech_One_xjror0.jpg'),
            ('SpeedOne Torpedo', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426876/Speedone_Torpedo_dlbij3.jpg'),
            ('Diamond', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427045/Diamond_bmihni.jpg'),
            ('Weapon Cannon35 BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426572/Weapon_Cannon_35_BOOST_ztsq0y.jpg'),
            ('Answer ProTaper 20x20', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426773/Answer_ProTaper_20x20_j3siyw.jpg'),
            ('Maxxis Ardent 29 x 2.25 Tanwall', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427142/Maxxis_Ardent_29_x_2.25_Tanwall_kd0zfg.jpg'),
            ('9 SPEED SUMC CP With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426641/SUMC_8_TO_12SPD_ctvl9s.jpg'),
            ('Weapon Wave', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426831/Weapon_Wave_nfxclt.jpg'),
            ('San Marco', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427032/San_marco_avpiyz.jpg'),
            ('WTB i25 Tubeless Ready', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426995/WTB_i25_ftnsx1.jpg'),
            ('Seer SILICON Hornet Bar Tape', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426818/Seer_SILICON_Hornet_du0foa.jpg'),
            ('Handle Bar Pro LT', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426780/Handle_Bar_Pro_LT_bv4qtj.jpg'),
            ('Manitou Mattoc Comp Boost', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426561/Manitou_Mattoc_Comp_BOOST_giu2n1.jpg'),
            ('11 SPEED SUMC CP With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426641/SUMC_8_TO_12SPD_ctvl9s.jpg'),
            ('Garuda Rampage', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426717/Garuda_Rampage_dgbdgg.jpg'),
            ('LDCNC 3.0', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426883/Hub_LDNC_3.0_tabrbo.jpg'),
            ('Genova Big Dipper', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426878/Hub_Genova_Big_Dipper_flh9zo.jpg'),
            ('Drop Bar Gravel Pro LT', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426786/Drop_Bar_Gravel_Pro_LT_bzvyov.jpg'),
            ('Manitou Machete Comp BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426550/Manitou_Machete_Comp_BOOST_pir353.jpg'),
            ('Handle Grip Attack Dual Lock-On', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426836/Handle_Grip_Attack_Dual_Lock-on_hjvcll.jpg'),
            ('Deore M6100 12spd Upkit with Weapon Cogs', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427168/Deore_M6100_12spd_l5zc79.jpg'),
            ('Fork Weapon Tower', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426580/Weapon_Tower_uhvrwr.jpg'),
            ('Origin8 NON BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426867/Origin_8_Microspline_Nonboost_jfiwfv.jpg'),
            ('Sagmit Chaser', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426693/Sagmit_Chaser_aiq264.jpg'),
            ('Sagmit 618 CNC Sealed Bearing', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426918/Sagmit_618_CNC_Sealed_Bearing_lqhjp8.jpg'),
            ('Ragusa R100', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426862/Ragusa_R100_uz33wj.jpg'),
            ('Answer ProTaper 7050 series Aluminum', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426771/Answer_ProTaper_7050_kv8cw2.jpg'),
            ('9SPD KMC Chain X Series GOLD', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426637/KMC_CHAIN_X_SERIES_GOLD_9_10_AND_12_SPD_qtbpjh.jpg'),
            ('Weapon Spartan 29', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426705/Weapon_Spartan_29_thq5iq.jpg'),
            ('Ragusa R-100', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427016/Ragusa_R-100_qf5sop.jpg'),
            ('Maxxis Rekon Race 27.5 x 2.25', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427136/Maxxis_Rekon_Race_27.5_x_2.25_dniapf.jpg'),
            ('Easydo ES-01', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427048/Easydo_ES-01_bsfe2y.jpg'),
            ('Weapon Predator Stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427072/Weapon_Predator_Stem_af8mnq.jpg'),
            ('Seer Art Racing Edition BarTape', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426825/Seer_Art_Racing_Edition_qw2ubf.jpg'),
            ('Sagmit Safarri', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426972/Sagmit_Safari_pwvups.jpg'),
            ('Weapon Fury stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427070/Weapon_Fury_Stem_wsrpm6.jpg'),
            ('10 SPEED SUMC Oilslick 116Links With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426645/SUMC_OILSLICK_8_10_11SPD_okx6nk.jpg'),
            ('Maxxis Ikon 29 x 2.20', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427131/Maxxis_Ikon_29_x_2.20_ifoafu.jpg'),
            ('MKS BM7', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426926/MKS_BM-7_cpuhoa.jpg'),
            ('Giant with Hole', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427056/Gian_With_Hole_zm5n1m.jpg'),
            ('12SPD KMC Chain X Series GOLD', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426637/KMC_CHAIN_X_SERIES_GOLD_9_10_AND_12_SPD_qtbpjh.jpg'),
            ('SIZE 26 LEO TUBE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427123/Leo_tire_size_20_xdqvlm.jpg'),
            ('MAXXIS TUBE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427109/Maxxis_Tube_29_nvqdqf.webp'),
            ('SpeedOne Pilot Carbon', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426864/Speedone_Pilot_Carbon_vdxis7.jpg'),
            ('MKS JAPAN GR-9', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426909/MKS_GR-9_vpcpun.jpg'),
            ('Ryder X2', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426689/Ryder_X2_pbancr.jpg'),
            ('Weapon Ambush Stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427083/Weapon_Ambush_Stem_h1tu4z.jpg'),
            ('Pinewood Trident Flux', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426697/Pinewood_Trident_Flux_izjvr0.png'),
            ('Ragusa CNC Sealed Bearing 712', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426928/Ragusa_CNC_Sealed_Bearing_712_mf1rcz.jpg'),
            ('Speedone Bazooka', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426977/Speedone_Bazooka_uj3bcj.jpg'),
            ('MountainPeak Monster', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426723/MountainPeak_Monster_mvzyoz.jpg'),
            ('Sagmit shadow', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426776/Sagmit_Shadow_furdpl.jpg'),
            ('Saturn Dione', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426695/Saturn_Dione_scq1du.jpg'),
            ('HandlePost ControlTech CLS', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427075/HandlePost_ControlTech_CLS_zuizl4.jpg'),
            ('SIZE 20 TIRE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427115/Size_16_tire_c4wobx.webp'),
            ('Weapon Animal', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426881/Hub_Weapon_Animal_t4jpbr.jpg'),
            ('SpeedOne Soldier BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426874/Speedone_Soldier_BOOST_cm01bl.jpg'),
            ('Weapon Rubix', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426829/Weapon_Rubix_mxh4sl.jpg'),
            ('ELVES NANDOR', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426715/ELVES_NANDOR_pgrnbw.jpg'),
            ('Drop Bar Gravel Pro Discovery', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426784/Drop_Bar_Gravel_Pro_Discovery_al5uhs.jpg'),
            ('12SPD KMC Chain X Series GREY', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426635/KMC_CHAIN_X_SERIES_10_TO_12_SPEED_yosheh.jpg'),
            ('Topgrade', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427040/Topgrade_niwacr.jpg'),
            ('Silicon Grip Seer 7mm', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426822/Silicon_SEER_Grip_7mm_yutbwd.jpg'),
            ('11 SPEED SUMC Oilslick 116Links With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426645/SUMC_OILSLICK_8_10_11SPD_okx6nk.jpg'),
            ('Ragusa R700', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426911/Ragusa_R700_d16khm.jpg'),
            ('GT-10 126links', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426642/GT-10_126links_kbpocx.jpg'),
            ('10 SPEED SUMC CP With Missing link', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426641/SUMC_8_TO_12SPD_ctvl9s.jpg'),
            ('SIZE 16 TIRE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427115/Size_16_tire_c4wobx.webp'),
            ('Specialized Stumpjumper', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426731/Specialized_Stumpjumper_wksj1t.png'),
            ('Maxxis Ardent Race 27.5 x 2.20', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427144/Maxxis_Ardent_Race_27.5_x_2.20_bcjh2v.jpg'),
            ('Speedone Floater BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426701/Speedone_Floater_BOOST_kvohnw.jpg'),
            ('SeatPost ControlTech ONE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427067/HandlePost_ControlTech_ina7ql.jpg'),
            ('Maxxis Ikon 29 x 2.20 Tanwall', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427133/Maxxis_Ikon_29_x_2.20_Tanwall_bejdbb.jpg'),
            ('Answer ProTaper', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426790/Answer_Pro_Taper_xztib4.jpg'),
            ('SR Suntour Raidon BOOST', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426568/SR_Suntour_raidon_BOOST_a9iqdw.jpg'),
            ('Weapon Stealth 29', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426707/Weapon_Stealth_29_glhbpk.png'),
            ('Giant w/o Hole', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427024/Gian_without_Hole_amofmr.jpg'),
            ('American Classic Feldspar 290 Tubeless Ready', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426997/American_Classic_Feldstar_290_zkkmer.jpg'),
            ('Seer POLYMER Hornet Bar Tape', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426840/Seer_Polymer_Hornet_mdpcoc.jpg'),
            ('Ryder X3 27.5 2021 MT200 Hydro Brakes (3x8)', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426691/Ryder_X3_27.5_2021_MT200_Hydro_Brakes_3x8_pyn7xf.jpg'),
            ('Jalco Maranello', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427000/Jalco_Maranello_Black_and_Red_r44zvz.jpg'),
            ('Sagmit Legend M32', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426980/Sagmit_Legend_clsrrk.jpg'),
            ('Mountainpeak Everest 2', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426721/Mountainpeak_Everest_2_ebnpbx.jpg'),
            ('LDCNC RS300 700c Rim Brake', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426989/LDCNC_RS300_700C_Rim_Brake_v5rba9.jpg'),
            ('CT-1HX 116links Heavy Duty for FIXIE', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426639/CT-1HX_116links_Heavy_Duty_for_FIXIE_hbuuul.jpg'),
            ('MKS Sylvan Touring', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426923/MKS_Sylvan_Touring_hpzge8.jpg'),
            ('Specialized Black', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427030/Specialized_Black_vbwezf.jpg'),
            ('Maxxis Ardent 27.5 x 2.25', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427139/Maxxis_Ardent_27.5_x_2.25_hql2fq.jpg'),
            ('Specialized M811', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427037/Specialized_M811_Silver_si24kx.jpg'),
            ('Weapon Beast Stem', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427086/Weapon_Beast_Stem_mp01ql.jpg'),
            ('HandlePost ControlTech', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427067/HandlePost_ControlTech_ina7ql.jpg'),
            ('Sagmit edison 12spd up kit', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427151/Sagmit_Edison_12spd_Up_Kit_yzgce1.jpg'),
            ('GT-11 126links', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426633/GT-11_126links_a5bbig.jpg'),
            ('Sagmit RedClassic skull', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776427027/Sagmit_Red_Classic_Skull_wvaswz.jpg'),
            ('Sagmit 622 CNC Sealed Bearing', 'https://res.cloudinary.com/dhsecafme/image/upload/v1776426921/Samit_622_CNC_Sealed_Bearing_wzxppx.jpg')
    ) AS updates(ProductName, ImageUrl)
    ON p.Name = updates.ProductName
) AS source
-- Match ONLY the primary image to avoid updating multiple non-primary images and breaking unique constraint
ON (target.ProductId = source.ProductId AND target.IsPrimary = 1)
WHEN MATCHED THEN
    UPDATE SET 
        target.ImageUrl = source.ImageUrl,
        target.StorageBucket = 'taurus-bikeshop-assets',
        target.StoragePath = source.ImageUrl,
        target.ImageType = 'Full'
WHEN NOT MATCHED BY TARGET THEN
    INSERT (ProductId, StorageBucket, StoragePath, ImageUrl, ImageType, IsPrimary, DisplayOrder, CreatedAt)
    VALUES (source.ProductId, 'taurus-bikeshop-assets', source.ImageUrl, source.ImageUrl, 'Full', 1, 0, GETUTCDATE());
