// WebApplication/Models/Entities/Order.cs

using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models.Entities;

/// <summary>
/// Core customer order record. Created at the end of the checkout flow and
/// updated throughout the order lifecycle by both the WebApplication and AdminSystem.
/// <para>
/// <b>Computed fields (never stored):</b>
/// <c>TotalAmount = SubTotal - DiscountAmount + ShippingFee</c> is computed in
/// <c>vw_OrderSummary</c>. It must never be stored as a column or property.
/// Use the view or calculate it inline in ViewModels.
/// </para>
/// <para>
/// <b>Order number format:</b> <c>TBS-YYYY-NNNNN</c> (e.g. TBS-2026-00001).
/// Generated by <c>OrderService.CreateOrderAsync</c> — unique enforced by
/// the database unique index on <see cref="OrderNumber"/>.
/// </para>
/// <para>
/// <b>OrderStatus flow:</b>
/// <list type="bullet">
///   <item>Online delivery: Pending → PendingVerification → Processing → OutForDelivery → Delivered</item>
///   <item>Store pickup: Pending → ReadyForPickup → PickedUp</item>
///   <item>Payment hold: Pending → OnHold</item>
///   <item>Cancellation: any non-terminal state → Cancelled</item>
/// </list>
/// Use <see cref="OrderStatuses"/> constants instead of magic strings for all
/// status comparisons and assignments.
/// </para>
/// <para>
/// <b>Walk-in POS orders:</b> <see cref="IsWalkIn"/> = true for orders created
/// via the AdminSystem POS terminal. These orders have no <see cref="ShippingAddressId"/>,
/// are created with status <c>Delivered</c> immediately, and use Cash or GCash payment only.
/// </para>
/// <para>
/// <b>Inventory locking:</b> When an order is created, <c>OrderService</c> writes
/// <c>InventoryLog</c> Lock entries for each item and decrements
/// <c>ProductVariant.StockQuantity</c>. When the order is delivered, Unlock + Sale
/// entries are written. When cancelled, Unlock entries are written and stock is restored.
/// All of this happens within a single DB transaction.
/// </para>
/// </summary>
public sealed class Order
{
    /// <summary>Primary key — auto-increment identity.</summary>
    public int OrderId { get; set; }

    /// <summary>FK to the customer who placed this order.</summary>
    public int UserId { get; set; }

    /// <summary>
    /// Human-readable unique order reference number (e.g. TBS-2026-00001).
    /// Generated by <c>OrderService</c> at order creation.
    /// Enforced unique by a unique index in the database.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string OrderNumber { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the order was placed.</summary>
    public DateTime OrderDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Current status of the order in its lifecycle.
    /// Constrained by CK_Order_Status to 9 valid values.
    /// Use <see cref="OrderStatuses"/> constants instead of magic strings.
    /// Status transitions are enforced in <c>OrderService.UpdateStatusAsync</c>.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string OrderStatus { get; set; } = OrderStatuses.Pending;

    /// <summary>
    /// Sum of all order line item totals (Quantity × UnitPrice) before any
    /// discounts or shipping fees are applied. Must be &gt;= 0.
    /// Set at order creation from cart items — never recalculated after that.
    /// </summary>
    public decimal SubTotal { get; set; }

    /// <summary>
    /// Voucher discount amount deducted from <see cref="SubTotal"/>.
    /// Zero when no voucher is applied. Must be &gt;= 0.
    /// Written by <c>VoucherService.ApplyAsync</c> at order creation.
    /// </summary>
    public decimal DiscountAmount { get; set; } = 0m;

    /// <summary>
    /// Courier or delivery fee added to the order total.
    /// Zero for store pickup orders. Must be &gt;= 0.
    /// Set during checkout based on the selected delivery method.
    /// </summary>
    public decimal ShippingFee { get; set; } = 0m;

    /// <summary>
    /// FK to the immutable address snapshot row used as the shipping destination.
    /// NULL for walk-in POS orders (<see cref="IsWalkIn"/> = true) which have
    /// no shipping address.
    /// The referenced Address row must have <c>IsSnapshot = true</c> — created
    /// by <c>CheckoutController</c> at order placement to permanently preserve
    /// the shipping address at the time of the order.
    /// </summary>
    public int? ShippingAddressId { get; set; }

    /// <summary>
    /// Customer contact phone number for delivery coordination.
    /// Optional — may differ from the user's profile phone number.
    /// </summary>
    [MaxLength(20)]
    public string? ContactPhone { get; set; }

    /// <summary>
    /// Free-text delivery instructions for the courier
    /// (e.g. "Leave at gate", "Call before delivery").
    /// </summary>
    [MaxLength(500)]
    public string? DeliveryInstructions { get; set; }

    /// <summary>
    /// <c>true</c> for orders created via the AdminSystem walk-in POS terminal.
    /// Walk-in orders have no shipping address, are immediately Delivered,
    /// and accept Cash or GCash payment only.
    /// </summary>
    public bool IsWalkIn { get; set; } = false;

    /// <summary>UTC timestamp when this order row was created.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// UTC timestamp of the last status change or any modification to this row.
    /// NULL until the first update. Set by the service layer on every mutation.
    /// Added in schema v8.2.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Logical-delete flag. When true the order is hidden from all queries.
    /// Physical rows are never deleted. Set by admin soft-delete. Added in schema v8.2.
    /// </summary>
    public bool IsDeleted { get; set; } = false;

    /// <summary>
    /// How the order will be fulfilled. Constrained by CK_Order_FulfillmentType
    /// to 'Delivery', 'Pickup', or 'WalkIn'. Added in schema v8.2.
    /// Use <see cref="FulfillmentTypes"/> constants instead of magic strings.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string FulfillmentType { get; set; } = FulfillmentTypes.Delivery;

    /// <summary>
    /// Payment method the customer chose at checkout (GCash or BankTransfer).
    /// Captured from <c>CheckoutViewModel.PaymentMethod</c> when the order is
    /// created so the payment upload page can render the correct instructions
    /// and resolve the correct <c>StorePaymentAccount</c> before the customer
    /// submits proof. Mirrored onto <c>Payment.PaymentMethod</c> at submission
    /// time. Added in schema v9.3.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string PaymentMethod { get; set; } = string.Empty;

    /// <summary>
    /// FK to GuestSession for orders placed without a registered account.
    /// NULL for all registered-user orders. Planned feature — added in schema v8.2.
    /// </summary>
    public int? GuestSessionId { get; set; }

    /// <summary>
    /// FK to the Cart that produced this order — used for cart-to-order lineage.
    /// NULL when lineage is not recorded. Added in schema v8.2.
    /// </summary>
    public int? CartId { get; set; }

    /// <summary>
    /// FK to the POS_Session during which this walk-in order was created.
    /// NULL for all online orders. Added in schema v8.2.
    /// </summary>
    public int? POSSessionId { get; set; }

    // -------------------------------------------------------------------------
    // Navigation properties
    // -------------------------------------------------------------------------

    /// <summary>The customer who placed this order.</summary>
    public User User { get; set; } = null!;

    /// <summary>
    /// The immutable shipping address snapshot for this order.
    /// NULL for walk-in POS orders.
    /// </summary>
    public Address? ShippingAddress { get; set; }

    /// <summary>
    /// All line items in this order. Quantity and UnitPrice are locked at
    /// order creation time and never modified.
    /// Cascade-deleted when the order is deleted.
    /// </summary>
    public ICollection<OrderItem> Items { get; set; } = new List<OrderItem>();

    /// <summary>
    /// All payment records associated with this order.
    /// Typically one payment per order, but the schema supports multiple
    /// (e.g. partial payment scenarios).
    /// </summary>
    public ICollection<Payment> Payments { get; set; } = new List<Payment>();

    /// <summary>
    /// Delivery records for this order.
    /// NULL for store pickup orders. Populated when a courier is booked
    /// by the AdminSystem.
    /// </summary>
    public ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();

    /// <summary>
    /// Store pickup metadata for this order.
    /// Only exists when the customer chose store pickup at checkout.
    /// 1:1 relationship — configured via HasOne/WithOne in AppDbContext.
    /// </summary>
    public PickupOrder? PickupOrder { get; set; }

    /// <summary>
    /// Voucher redemption records associated with this order.
    /// At most one VoucherUsage per order in standard flow.
    /// </summary>
    public ICollection<VoucherUsage> VoucherUsages { get; set; } = new List<VoucherUsage>();

    /// <summary>
    /// Customer reviews submitted for products in this order.
    /// Reviews can only be submitted after the order reaches Delivered status.
    /// </summary>
    public ICollection<Review> Reviews { get; set; } = new List<Review>();

    /// <summary>
    /// Support tickets linked to this order.
    /// A customer can raise a ticket referencing this order from the dashboard
    /// or the delivery review flow.
    /// </summary>
    public ICollection<SupportTicket> SupportTickets { get; set; } = new List<SupportTicket>();

    /// <summary>
    /// Inventory log entries associated with this order.
    /// Includes Lock entries (at order creation), Unlock entries (at delivery
    /// confirmation or cancellation), and Sale entries (at delivery confirmation).
    /// </summary>
    public ICollection<InventoryLog> InventoryLogs { get; set; } = new List<InventoryLog>();

    /// <summary>
    /// Notification rows queued for this order (e.g. OrderConfirmation,
    /// TrackingUpdate, ReadyForPickup, DeliveryConfirmation).
    /// </summary>
    public ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}

/// <summary>
/// Compile-time constants for the FulfillmentType column on <see cref="Order"/>.
/// Mirrors the CK_Order_FulfillmentType CHECK constraint added in schema v8.2.
/// </summary>
public static class FulfillmentTypes
{
    /// <summary>Courier delivery to the customer's address (default).</summary>
    public const string Delivery = "Delivery";

    /// <summary>Customer collects from the store.</summary>
    public const string Pickup = "Pickup";

    /// <summary>Walk-in POS sale — fulfilled immediately at the counter.</summary>
    public const string WalkIn = "WalkIn";
}

/// <summary>
/// Compile-time constants for all valid order status values.
/// Mirrors the CK_Order_Status CHECK constraint in the database (9 values).
/// Use these instead of magic strings for all status comparisons and assignments
/// throughout <c>OrderService</c>, <c>CheckoutController</c>, and background jobs.
/// </summary>
public static class OrderStatuses
{
    /// <summary>
    /// Order has been placed and is awaiting payment confirmation or admin action.
    /// Initial status for all online orders.
    /// </summary>
    public const string Pending = "Pending";

    /// <summary>
    /// Bank transfer proof has been uploaded and is awaiting admin verification.
    /// Set by <c>PaymentService</c> after proof upload.
    /// </summary>
    public const string PaymentVerification = "PendingVerification";

    /// <summary>
    /// Order has been placed on hold — typically due to payment verification
    /// timeout (24-hour deadline exceeded). Set by <c>PaymentTimeoutJob</c>.
    /// </summary>
    public const string OnHold = "OnHold";

    /// <summary>
    /// Payment confirmed and order is being prepared for dispatch.
    /// Set by AdminSystem after payment verification approval.
    /// </summary>
    public const string Processing = "Processing";

    /// <summary>
    /// Order is ready for customer collection at the store.
    /// Set by AdminSystem for pickup orders. Triggers ReadyForPickup notification.
    /// </summary>
    public const string ReadyForPickup = "ReadyForPickup";

    /// <summary>
    /// Customer has collected their order from the store.
    /// Set by AdminSystem when pickup is physically confirmed.
    /// </summary>
    public const string PickedUp = "PickedUp";

    /// <summary>
    /// Order has been picked up by the courier (Lalamove or LBC) and is out for delivery.
    /// Set by AdminSystem after courier booking is confirmed.
    /// </summary>
    public const string OutForDelivery = "OutForDelivery";

    /// <summary>
    /// Order has been successfully delivered to the customer.
    /// Set by <c>DeliveryStatusPollJob</c> or AdminSystem on delivery confirmation.
    /// Triggers Unlock + Sale InventoryLog entries and enables review submission.
    /// </summary>
    public const string Delivered = "Delivered";

    /// <summary>
    /// Order has been cancelled. Stock is unlocked and restored.
    /// Can be set from any non-terminal status by customer or admin.
    /// </summary>
    public const string Cancelled = "Cancelled";
}